---
# Download packages for postgres tasks

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - unzip

- name: create db user
  user: name={{dbuser}} group=admin shell=/bin/bash append=yes

- name: ensure database is created
  sudo_user: postgres
  postgresql_db: name={{dbname}}

- name: ensure user has access to database
  sudo_user: postgres
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure user does not have unnecessary privilege
  sudo_user: postgres
  postgresql_user: name={{dbuser}} role_attr_flags=SUPERUSER,NOCREATEDB

- name: download db tables
  get_url: url=http://db-sharing.s3.amazonaws.com/HRM-Data.zip dest=/tmp/HRM-Data.zip mode=0777

- name: unzip db tables
  unarchive: src=/tmp/HRM-Data.zip dest=/tmp copy=no

- name: Copy over postgres scripts
  template:  src=postgres/templates/{{item}}.sql dest=/tmp/{{item}}.sql
  with_items:
    - createTables
    - importCSV

- name: create tables and import data
  sudo_user: postgres
  shell: /usr/bin/psql -d {{dbname}} -f /tmp/{{item}}.sql
  with_items:
    - createTables
    - importCSV



